version: '3.8'

services:
  # Search Engine
  elasticsearch:
    image: elasticsearch:7.17.15
    container_name: doc-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - doc-net

  # Analytics Dashboard
  kibana:
    image: kibana:7.17.15
    container_name: doc-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - doc-net

  # Document Parser
  tika:
    image: apache/tika:latest-full
    container_name: doc-tika
    restart: unless-stopped
    ports:
      - "9998:9998"
    networks:
      - doc-net

  # OCR Service (Simple Python-based)
  ocr:
    image: jbarlow83/ocrmypdf
    container_name: doc-ocr
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - doc-net

  # AI Processing
  ollama:
    image: ollama/ollama:latest
    container_name: doc-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - doc-net

  # Object Storage
  minio:
    image: minio/minio:latest
    container_name: doc-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - doc-net

  # Processing Pipeline
  node-red:
    image: nodered/node-red:latest
    container_name: doc-node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red:/data
      - ./data/input:/input
      - ./data/processed:/processed
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - elasticsearch
      - tika
      - minio
      - ollama
    networks:
      - doc-net

  # Cache
  redis:
    image: redis:alpine
    container_name: doc-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - doc-net

networks:
  doc-net:
    driver: bridge