cluster.name: "document-processing-cluster"
node.name: "doc-node-1"
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node

# Security
xpack.security.enabled: false
xpack.monitoring.collection.enabled: false

# Performance
bootstrap.memory_lock: false
indices.memory.index_buffer_size: 30%
thread_pool.search.queue_size: 1000

# Index settings
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 5s

# Logging
logger.level: WARN