server.name: "document-kibana"
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.requestTimeout: 90000
elasticsearch.pingTimeout: 3000

# Security
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long_for_encryption"

# UI Settings
server.defaultRoute: "/app/discover"